from t_client.operation_service.operation_types import OperationTypes

print(OperationTypes.OPERATION_TYPE_BOND_TAX.get_ru_str)
print(OperationTypes.OPERATION_TYPE_BOND_TAX.get_operation_id)

print(OperationTypes.get_name_by_id(999))